### PR TITLE
Add script for windows integration

### PR DESCRIPTION
**Pull request by taste1981**

### CODE REVIEW

**Review by jianjunz — COMMENTED** [review]
`build.py` is expected to support all platforms. One difference between Linux and Windows is the name of output file. Can we simply make it support Windows by determining the output file name at runtime?

**Comment by taste1981** [comment]
Then I suppose you should lower the python version required, and make sure you don't use /, but instead use \ for pathes in build.py.

**Comment by jianjunz** [comment]
Can we close this PR? `build.py` works for Windows now.

**Comment by taste1981** [comment]
> Can we close this PR? `build.py` works for Windows now.

Will close this.

**Pull request closed without merging**
